### ISSUE TITLE
user cannot be used as a SageMaker execution role

### ISSUE THREAD

**Issue by gatheluck** [gatheluck/SageMakerSdkSandbox#2]
## What

When try to run `scripts/1-1_hello_sagemaker_trainig.py`, following error happened. 

```bash
% poetry run python3 scripts/1-1_hello_sagemaker_trainig.py

Couldn't call 'get_role' to get Role ARN from role name <USER_NAME> to get Role path.
Traceback (most recent call last):
  File "/home/gatheluck/Scratch/SageMakerSdkSandbox/scripts/1-1_hello_sagemaker_trainig.py", line 14, in <module>
    role=sagemaker.get_execution_role(),
  File "/home/gatheluck/Scratch/SageMakerSdkSandbox/.venv/lib/python3.10/site-packages/sagemaker/session.py", line 5432, in get_execution_role
    raise ValueError(message.format(arn))
ValueError: The current AWS identity is not a role: arn:aws:iam::XXXXXXXXXXXX:user/<USER_NAME>, therefore it cannot be used as a SageMaker execution role
```

**Comment by gatheluck** [comment]
According to following article: https://stackoverflow.com/questions/47710558/the-current-aws-identity-is-not-a-role-for-sagemaker

> From inside these notebooks, get_execution_role() will return the IAM role name that was passed in as part of the notebook creation. That allows the notebook examples to be executed without code changes. From outside these notebooks, get_execution_role() will return an exception because it does not know what is the role name that SageMaker requires.

**Comment by gatheluck** [comment]
https://github.com/aws/sagemaker-python-sdk/issues/300#issuecomment-1431539831

> Inside SageMaker we can have multiple notebook instances and each notebook instance can have a different IAM role. When running your code locally get_execution_role will not work since there might be several roles dedicated to different SageMaker notebook instances. Therefore, you have to choose which is the right role to use.
> 
> In order to make your code work in both local and remote modes, you could instantiate a variable containing the specific value of IAM role, and implement a try block like here below.
>

```python
local_variable_for_sm_role = “arn:aws:iam::XXXX:role/service-role/XXXXX”
try:
    role = sagemaker.get_execution_role()
except ValueError:
    role = local_variable_for_sm_role
```

**Comment by gatheluck** [comment]
Offical AWS docs explain how to create role for SageMaker: https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-roles.html
